# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20160317_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='Sname',
            field=models.CharField(max_length=30),
        ),
    ]
